### ISSUE TITLE
OUJS Notice

### ISSUE THREAD

**Issue by Martii** [liquorburn/JSchain#1]
Since you haven't updated in a while you have an issue that has come to our attention [here](https://openuserjs.org/scripts/burn/Youtube_Persist_Worldwide/issues/Meta_Issue).

Please pay us a visit soon.

Thanks,
OUJS Admin.

P.S. Apologies for this repo issue visit since it's probably unrelated but it's the only way to impress upon you the importance of the issue.

**Comment by liquorburn** [comment]
Hi, thanks for updating my userscript "Youtube Persist Worldwide". I've made another commit (updated version into cversion variable). My apologies for not being there in the last weeks... So now, how to remove the flag?

**Comment by Martii** [comment]
Flag is removed. Usually we don't like to edit scripts but because it was related to the TM mess it was scanned and found to be needed. Thanks for getting back. :)

I see I missed the embedded version number too. Nice catch.

OUJS Admin
